title: Edward Kim # your name (or website title) here
logo: # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Contact: 
  <br><br>
  Phone: (858)997-3948
  
  Email: edykim187@gmail.com
  <br><br>
  Recently graduated with a M.S. in Public Health Data Science.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
